apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  description: | 
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
    - name: image-context
      type: string

  workspaces:
    - name: shared-data
    - name: docker-credentials

  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: main
        - name: gitInitImage
          value: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.44.5"
    
    - name: get-git-tag
      runAfter: ["fetch-source"]
      taskRef:
        name: git-cli-get-tag
      workspaces:
        - name: source
          workspace: shared-data

    - name: build-push
      runAfter: ["get-git-tag"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: $(params.image-reference):$(tasks.get-git-tag.results.tag)
        - name: EXTRA_ARGS 
          value: 
            - "--destination=$(params.image-reference):latest"
        - name: CONTEXT
          value: $(params.image-context)
  
