apiVersion: v1
kind: Namespace
metadata:
  name: vote-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vote-app
  name: tekton-helm-role
rules:
- apiGroups: [""]
  resources: ["pods", "secrets", "configmaps", "services", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: vote-app
  name: tekton-helm-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: tekton-helm-role
  apiGroup: rbac.authorization.k8s.io

