apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.frontend.name }}
  {{- with .Values.services.frontend.selectorLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.frontend.service.type }}
  ports:
    - port: {{ .Values.services.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- with .Values.services.frontend.selectorLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
